const itemTemplates = {
  personal: {
    placeholders: {
      firstName: "First Name",
      lastName: "Last Name",
      title: "Title",
      address: "City, Province/State, Country",
      phone: "Phone Number",
      email: "Email Address",
      bio: "Short Bio",
    },
    placeholderClasses: {
      firstName: "first-name",
      lastName: "last-name",
      title: "title",
      address: "address",
      phone: "phone",
      email: "email",
      bio: "bio",
    },
    dataType: "personal",
    dataTitleLong: "PERSONAL DETAILS",
    dataTitleShort: "Personal",
    dataHasButtons: false,
  },
  experience: {
    placeholders: {
      organization: "Organization/Company Name",
      location: "City, Country",
      from: "From",
      to: "To",
      role: "Role",
      description: "Role Description",
    },
    placeholderClasses: {
      organization: "organization",
      location: "location",
      from: "from-time",
      to: "to-time",
      role: "role",
      description: "description",
    },
    dataType: "experience",
    dataTitleLong: "WORK EXPERIENCE",
    dataTitleShort: "Experience",
    dataHasButtons: true,
  },
  education: {
    placeholders: {
      organization: "School/College/University Name",
      location: "City, Country",
      from: "From",
      to: "To",
      degree: "Degree",
      field: "Field Of Study",
    },
    placeholderClasses: {
      organization: "school",
      location: "location",
      from: "from-time",
      to: "to-time",
      degree: "degree",
      field: "field",
    },
    dataType: "education",
    dataTitleLong: "EDUCATION",
    dataTitleShort: "Education",
    dataHasButtons: true,
  },
};

export default itemTemplates;
